# Generated by Django 3.0.1 on 2020-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200524_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(choices=[('Rolex', 'Rolex'), ('Audemars Piguet', 'Audemars Piguet'), ('Patek Philippe', 'Patek Philippe'), ('Richard Mille', 'Richard Mille'), ('Cartier', 'Cartier')], default='', max_length=100),
        ),
    ]
