# Generated by Django 3.0.1 on 2020-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200525_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Brand new', 'Brand new'), ('Used but good', 'Used but good'), ('Used but worn', 'Used but worn'), ('Sold', 'Sold')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Rolex', 'Rolex'), ('Audemars Piguet', 'Audemars Piguet'), ('Patek Philippe', 'Patek Philippe'), ('Richard Mille', 'Richard Mille'), ('Cartier', 'Cartier')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
