# Generated by Django 3.0.1 on 2020-05-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200526_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mainImage',
            new_name='main_image',
        ),
    ]
