# Generated by Django 3.0.1 on 2020-05-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200526_0147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
