# Generated by Django 3.0.1 on 2020-06-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Preowned', 'Preowned'), ('Unworn', 'Unworn'), ('Sold', 'Sold')], default='', max_length=20),
        ),
    ]
